'use client';
import "./globals.css";
import { AuthProvider } from "@/app/contexts/AuthContext";
import { HotelProvider } from "@/app/contexts/HotelContext";
import { BookingProvider } from "@/app/contexts/BookingContext";
import { UserProvider } from "@/app/contexts/UserContext";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </head>
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <UserProvider>
            <HotelProvider>
              <BookingProvider>  
                {children}
              </BookingProvider>
            </HotelProvider>
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
